name: Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19' 
      - name: test & coverage report creation
        run: |
          go test ./... --timeout=10m